### ISSUE TITLE
(NeedsDefinition) Define a name for POA ERC20 token

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/parity-bridge#15]
https://github.com/poanetwork/parity-bridge/blob/master/contracts/bridge.sol#L267
```
    string public name = "ForeignBridge";

```
it will be shown on every DEX.
we also need to add `symbol = "POA"` in order to follow ERC20 standard

I propose for `"POA ERC20"` as a name of the token

@akolotov, @igorbarinov  thoughts?

**Comment by igorbarinov** [comment]
Я думал про POA20 для упрощения ПиОЭй Туени
есть примеры использовация чисел в имени токена кстати?

**Comment by igorbarinov** [comment]
I meant POA20 
Are there any examples of using numbers in a token name?

**Comment by rstormsf** [comment]
name doesn't matter, `symbol` is more important. Name could be "POA erc20 representation", etc.
symbol should be short

https://coinmarketcap.com/currencies/firstblood/ = 1ST

![image](https://user-images.githubusercontent.com/9360827/36127805-0bbf6378-1014-11e8-8974-34df7a262099.png)

**Comment by igorbarinov** [comment]
Sure, I don't think it's good to have POA on POA and POA on Foundation because it's ambiguous 
POA20 will state that it is ERC20 compatible token. ERC now EIP. I suppose we can leave only the number which will identify the nature of token

**Comment by rstormsf** [comment]
ok, should we have
```
name = 'POA ERC20 Foundation'
symbol = 'POA20'
```
?

**Comment by akolotov** [comment]
The funny thing is that `POA20` could be read as 'POA 2.0' :)

**Comment by banteg** [comment]
What about WPOA akin to WETH?

**Comment by igorbarinov** [comment]
didn't know about weth
more info https://weth.io/

**Comment by igorbarinov** [comment]
I like 
- Alex point of POA 2.0. Tokenized native currency sounds like high level of abstraction
- that it's easy to pronounce "pí ó é twɛ́nti" than "də́bəlyu pí ó é"

**Comment by akolotov** [comment]
@rstormsf should we close it?

**Comment by igorbarinov** [comment]
I'd like to add `on` 

```
name = 'POA ERC20 on Foundation'
symbol = 'POA20'
```

I'm fine with it

**Comment by akolotov** [comment]
So, @rstormsf please close this issue as soon as you update the contract in https://github.com/poanetwork/poa-parity-bridge-contracts

**Comment by igorbarinov** [comment]
@akolotov he'll assing it to himself in Waffle and move to bottom so we'll know it's less important

**Comment by akolotov** [comment]
@rstormsf  could we have a final tool/script/whaterver in the repo which will be used to deploy token contract. The name and symbol of the token will be specified there as so we can manage it through source control system.

**Comment by rstormsf** [comment]
? 
@akolotov it's just a contract with parameters...what do you want? 
https://github.com/poanetwork/poa-parity-bridge-contracts/blob/upgradable/migrations/3_upgradeable_deployment.js#L19
