### ISSUE TITLE
(Fix) Sync with upstream

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/parity-bridge#2]
Problem:
- our temp changes are in master branch and it's hard to sync with parity
Solution:
- move commits from master to your branch
- sync with upstream

**Comment by vbaranov** [comment]
- latest commits are moved to `poa-dev` branch
- master branch is synced with upstream: https://github.com/poanetwork/parity-bridge/commit/199e7ec271a94d5ba41fcfebbd1d1f6839922263

**Comment by igorbarinov** [comment]
![image](https://user-images.githubusercontent.com/424628/35180520-f17486f2-fd66-11e7-9b66-02fb04ccd3a0.png)
it shows that master is ahead.. 
https://help.github.com/articles/syncing-a-fork/

**Comment by igorbarinov** [comment]
@vbaranov, please sync again

**Comment by vbaranov** [comment]
@igorbarinov

![screen shot 2018-01-20 at 21 26 12](https://user-images.githubusercontent.com/4341812/35186661-cd2760cc-fe28-11e7-9573-0dd68c527c4c.png)

![screen shot 2018-01-20 at 21 34 13](https://user-images.githubusercontent.com/4341812/35186717-ba0c546a-fe29-11e7-8ce8-b80858460f7c.png)

I've already synced it with paritytech/parity-bridge.git master branch. These 53 commits - it is our support of ERC-20 token at the right side and javascript tests of the contracts with some sample setups. Don't you want to track our changes in master branch? Could you clarify?

**Comment by igorbarinov** [comment]
Let's have our changes in a separate branch. Master branch we need to have in full sync with upstream.

**Comment by vbaranov** [comment]
Ok. Master branch is fully synced with upstream now. Our changes are in other branches.

**Comment by igorbarinov** [comment]
What is difference between poa-dev and poa-dev2 branches?

**Comment by vbaranov** [comment]
`poa-dev` - is dev branch tested successfully with our demos, not merged with upstream
`poa-dev2` is dev branch with upstream, not tested yet
