### ISSUE TITLE
Implement a script to deploy bridge contracts

### ISSUE THREAD

**Issue by akolotov** [poanetwork/parity-bridge#30]
Since we have a new version of bridge contracts (https://github.com/poanetwork/poa-parity-bridge-contracts/commit/d53ae359653ee04df650576b53347d256c9a7f56) which complitely different from the original parity-bridge contracts, it is necessary to change deployment code in the bridge. But in order to be more undependent in maintanance of the deployment code, it is being suggested to implement it in form of a js/python/... script (the langugage is discussible).

The script must:
1. read the configuration `toml` file
2. deploy contracts with set of parameters given from configuration file
3. write the database file

**Comment by rstormsf** [comment]
1. read what exactly? for validators? 
2. what params?

**Comment by rstormsf** [comment]
done
https://github.com/poanetwork/poa-parity-bridge-contracts/tree/master/deploy
