### ISSUE TITLE
(Feature) Add support to communicate with networks by RPC

### ISSUE THREAD

**Issue by akolotov** [poanetwork/parity-bridge#4]
Currently parity-bridge assumes that full nodes of networks are configured on the same system where the bridge is run. Therefore it communicates to the nodes by using IPC. This cause several limitations:
* Requirements to the network bandwidth and the system performance/capacity should be   quite high: the system must have enough space to keep two blockchains and must verify   all new appeared blocks. So, it means that maintaining one bridge instance withing   the cloud could be quite expensive solution.
* The availability of the bridge software depends on the reliability of the particular Ethereum network client software. If an Ethereum client is not operaing (e.g. it crashes accidentally), the bridge software is not operating as well.
  
The way to avoid these limitations is to introduce ability for the bridge to communicate to full nodes through RPC. It will increase responsiveness of the bridge slightly which should not cause big issues due to the current nature of transactions confirmation mechanism used in the blockchain (there is no strict guarantee of a transaction inclusion into the next block).
  
Changes required:
---- 
1. Change _bridge/src/config.rs_ to
   * support the configuration parameters _rpc_host_ and _rpc_port_;
   * introduce the parameter _keystore_ to keep the path to the directory where files with      private keys are stored, this parameter is not subordinated to any section of the  configuration file since it is common for entire bridge;
   * extend sections _[home]_ and _[foregin]_ with parameter _password_ which contains      path to the file with password to decrypt the corrsponding key file to extract       the private key of the account responsible for signing transactions related      this side of the bridge.
2. Change _bridge/src/app.rs_ to provide the ability to connect through RPC. The following    logic of connection channel selection should be implemented: if the parameter _ipc_ is    specified the IPC connection must be setup even if _rpc_host_ is specified. If _rpc_host_    specifed but there is no configuration for the parameter _rpc_port_ the port 8545 is used    by default.
3. Extend the functionality of sending transactions to sign them by using private key of    the corresponding account and sending them through _sendRawTransaction_ functionality.    Encrypted key for the bridge authority account must stored in a separate file.    This approach requires to use _network id_ of the corresponding blockchain and _NOnce_    (number of operation) of the corresponding account.
4. Introduce new parameters _home_network_id_, _home_account_nonce_, _foreign_network_id_    and _home_account_nonce_ in the database in order to get rid of requests to the IPC/RPC    nodes to track _network id_ and _NOnce_ required to sign transactions.    A new paramter `authority_keystore` must keep a path to the keystore file with the     private key of the bridge authority. This parameter should not belong any node in    in the configuration file.

**Comment by yrashk** [comment]
One of the challenges of RPC will be the subscriptions. While not impossible, of course (there's polling), they will be somewhat saturating as we'll need to poll frequently.  Considering that it most likely will have to go over HTTPS, there's also going to be a sligh cryptography-related penalty here as well. Need to check if keep-alive penalty can be avoided. There's another option to use websockets, but that might be not the best answer operations-wise. Again, as mentioned in the original issue, the delays might not be a big of an issue. But I thought it would be worth mentioning some downsides of using RPC.

**Comment by rstormsf** [comment]
@yrashk what about websockets?

**Comment by akolotov** [comment]
addressed by @yrashk in #41 and #46
