### ISSUE TITLE
Dynamic gas_price on foreign network

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/parity-bridge#48]
Bridge should read from config.toml

```
gas_price_oracle_url = "https://gasprice.poa.network/"
gas_price_speed_type = "fast"
```

and receive this value in gwei, convert to hex value in wei for signing tx on foreign.
this value could be cached only for short period of time ( 5-10min)

**Comment by akolotov** [comment]
This is a duplicate for https://github.com/poanetwork/parity-bridge/issues/16.
