### ISSUE TITLE
(Feature) Implement Owners of contracts

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/parity-bridge#8]
We have to think about who can upgrade contracts and who can deploy them
Those authorities should not be validators.

**Comment by akolotov** [comment]
@rstormsf we agreed to have a multisig wallet implemented to manage the bridge contract. So far I see only `Ownable` contract and there is no procedure which describes how to manage bridge contracts by the mutlisig wallet. Could we have this issue opened till the process will be completly understood/described/implemented?

**Comment by rstormsf** [comment]
@akolotov 
1. You can make an owner a multisig contract

**Comment by akolotov** [comment]
Good. And what is the next? How can I invoke, for example, `setGasLimitWithdrawRelay()` on Home bridge side?
