### ISSUE TITLE
Extend tracebility of deposits transactions

### ISSUE THREAD

**Issue by akolotov** [poanetwork/parity-bridge#9]
Currently every bridge instance sends `deposit()` to the _Foreign_ side to confirm transfer of funds. But only transaction which allow to reach `requiredSignatures` limit generates an event.

<a href="https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgYnJpZGdlIGRlcG9zaXQgKGZsb3cgIHdpcmggMwAWB3MgaW4gYWN0aW9uKQoKcGFydGljaXBhbnQgIkhvbWUgQWNjb3VudCIgYXMgSEEADhNzaWRlXG5Db250cmFjACEHQwA7DkIAgQIFXG5JbnN0YW5jZSAjMQBLBUIxAAggMgAiBjIAMCAzAEoGMwCBMw5Gb3JlaWduAIEPFEZDCgpIQS0-K0hDOiBldGhlcgpub3RlIGxlZnQgb2YgSEMKICAgIGFzc29zaWF0ZWQACgV3aXRoIHR4IGlkCmVuZCBub3RlCkhDLT5CMTogRACCXwYoc2VuZGVyLCB2YWx1ZSkAGQYyAAIdLUIzACYZAIEQBW92ZXIgQjEsIEIyLCBCMwCBEgh1bWVkIHRoYXQAgSYFAHIGID09IHJlY2lwaWVudACBGwpCMS0-K0ZDOgCEAwgoABsJAIEiBywAgVEGKQpGQy0-LUZDOiAxc3Qgc2lnbmF0dXJlIHJlY2VpdmVkCkIyABkxMm5kADUVMwBoLEZDOiAzcgA0FQCBKgkic3RhdGVcbmNvbW1pdGVkIgo&s=rose" 
   target="_blank">
  <img src="https://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgYnJpZGdlIGRlcG9zaXQgKGZsb3cgIHdpcmggMwAWB3MgaW4gYWN0aW9uKQoKcGFydGljaXBhbnQgIkhvbWUgQWNjb3VudCIgYXMgSEEADhNzaWRlXG5Db250cmFjACEHQwA7DkIAgQIFXG5JbnN0YW5jZSAjMQBLBUIxAAggMgAiBjIAMCAzAEoGMwCBMw5Gb3JlaWduAIEPFEZDCgpIQS0-K0hDOiBldGhlcgpub3RlIGxlZnQgb2YgSEMKICAgIGFzc29zaWF0ZWQACgV3aXRoIHR4IGlkCmVuZCBub3RlCkhDLT5CMTogRACCXwYoc2VuZGVyLCB2YWx1ZSkAGQYyAAIdLUIzACYZAIEQBW92ZXIgQjEsIEIyLCBCMwCBEgh1bWVkIHRoYXQAgSYFAHIGID09IHJlY2lwaWVudACBGwpCMS0-K0ZDOgCEAwgoABsJAIEiBywAgVEGKQpGQy0-LUZDOiAxc3Qgc2lnbmF0dXJlIHJlY2VpdmVkCkIyABkxMm5kADUVMwBoLEZDOiAzcgA0FQCBKgkic3RhdGVcbmNvbW1pdGVkIgo&s=rose" 
       alt="bridge deposit (simple flow)" 
       width="750" />
</a>

Proposal for changes
---- 
In order to simplify issues investigation process it makes sense to generate events on every unique and valid `depost()` transactions. 

The suggestion is to raise `SignedForDeposit(address indexed, bytes32)` with the bridge address and id of the transaction originating deposit request on the _Home_ (left) side:
* the brigde address will allow to filter transactions from the specific bridge;
* the tx id will allow to match the transaction on the _Home_ side and bridge resposes on the _Foreign_ side. 

Prior to merge of these changes it is necessary to understand how gas consumption is being increased and get agreement that it is acceptable.

**Comment by rstormsf** [comment]
I support this idea

**Comment by akolotov** [comment]
* Yes. it needs to be implemented in `deposit()` of `ForeignBridge`.
* `transferAndCall()` will generate `Withdraw()` event similar to `transferHomeViaRelay` (https://github.com/poanetwork/parity-bridge/blob/master/contracts/bridge.sol#L423-L436).
* but you are right it makes sense to implement `SignedForWithdraw(address indexed, bytes32)` in `submitSignature()`.
